config/routes.rb
Lab11App::Application.routes.draw do
  resources :products, except: [:show]

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new released_date: Time.now
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :model, :released_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.slim
doctype html

head
  meta charset="utf-8"
  meta name="viewport" content="width=device-width"
  title= "Product Info"
  = stylesheet_link_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tag

body
  .navbar.navbar-fixed-top
    .navbar-inner
      .container
        a.btn.btn-navbar data-toggle="collapse" data-target=".nav-collapse"
          span.icon-bar
          span.icon-bar
        a.brand href="#" Product Details
        .nav-collapse
          ul.nav
            li= link_to "Home", products_path
            li= link_to "About"
  .container
    .row
      .span12= yield
    br
  footer
    .row
      .span12 &copy;418342

= javascript_include_tag 'application', 'data-turbolinks-track' => true

javascript:

app/views/products/_form.html.slim
= form_for @product do |f|
  .controls.span5
    = f.label :name
    = f.text_field :name
  .controls.span5
    = f.label :model
    = f.text_field :model
  .controls.span5
    = f.label :released_date
    = f.date_field :released_date
    br
    = f.button :submit, :class => 'btn btn-success'
    == "&nbsp;"
    = link_to t('.cancel'), products_path, :class => 'btn btn-warning'

app/views/products/edit.html.slim
- model_class = Product
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/products/index.html.slim
- model_class = Product
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:model)
      th= model_class.human_attribute_name(:released_date)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @products.each do |product|
      tr
        td= product.id
        td= product.name
        td= product.model
        td= product.released_date
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(product), :class => 'btn btn-mini'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(product), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_product_path, :class => 'btn btn-primary'

app/views/products/new.html.slim
- model_class = Product
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"